services:
  db:
    container_name: "notesdb"
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
#    ports:
#      - "5438:5432" # для локального запуска
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    container_name: "notesapp"
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
#    volumes: # для локального запуска
#      - .:/app

volumes:
  postgres_data:
